sudo: required

services:
  - docker

addons:
  apt:
    packages:
      - docker-ce

env:
  DOCKER_COMPOSE_VERSION: 1.8.1

before_install:
  - sudo rm /usr/local/bin/docker-compose
  - curl -L https://github.com/docker/compose/releases/download/${DOCKER_COMPOSE_VERSION}/docker-compose-`uname -s`-`uname -m` > docker-compose
  - sudo mv docker-compose /usr/local/bin
  - chmod +x /usr/local/bin/docker-compose

  - docker --version

  - docker build -q -t vfac/envdevphpbase:7.4-fpm-alpine .

  - docker run --name php7.4-fpm-alpine -d -v $PWD:/var/www/html vfac/envdevphpbase:7.4-fpm-alpine

script:
  - docker exec php7.4-fpm-alpine php -v
  - docker exec php7.4-fpm-alpine sh -c "php -v | grep 7.4"
  - docker exec php7.4-fpm-alpine composer --version
  - docker exec php7.4-fpm-alpine ps |grep php-fpm
