name: Docker Image CI EnvDevPHPBase 7.4 FPM Alpine

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Build the Docker image EnvDevPHPBase 7.4 FPM Alpine
        run: docker build . --file Dockerfile --tag vfac/envdevphpbase:7.4-fpm-alpine
